#!/usr/bin/env bash
# changes the following domain resolve ips
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

# Function to update /etc/hosts file
update_hosts_file() {
    sudo sed -i 's/^127.0.0.1[[:space:]]localhost$/127.0.0.2 localhost/' /etc/hosts
    sudo sed -i 's/^.*facebook.com$/8.8.8.8 facebook.com/' /etc/hosts
}

# Check if Docker is running
if [ "$(systemctl is-active docker)" = "active" ]; then
    # Docker is running, update hosts file
    update_hosts_file
    echo "Hosts file updated successfully."
else
    echo "Docker is not running. Please make sure Docker is running before running this script."
fi
