#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.
# a different way using ifconfig but now ip is a new command and ifconfig can be missing in some os
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'
#ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
#chmod +x 1-show_attached_IPs.sh
#./1-show_attached_IPs.sh
sudo apt install net-tools
if command -v ip &> /dev/null; then
    # Use ip command to get IPv4 addresses
    sudo apt install net-tools
    ip addr show | awk '/inet / {print $2}' | cut -d '/' -f1
elif command -v ifconfig &> /dev/null; then
    # Use ifconfig command as fallback
    ifconfig | awk '/inet / {print $2}' | cut -d ' ' -f2
elif command -v hostname &> /dev/null; then
    # Use hostname command as another fallback
    hostname --all-ip-addresses
else
    echo "Unable to retrieve IPv4 addresses. No suitable command found."
fi
